name: CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print environment info
        run: |
          echo "Repository is alive"
          uname -a
          date

      - name: Simulate build
        run: |
          echo "No code yet, but pipeline works"

      - name: Success
        run: echo "Pipeline finished successfully"